#!/bin/sh
#curl -o /tmp/install_license https://raw.githubusercontent.com/Kaitiz/Surveillance-Station/main/lib/SurveillanceStation-armada38x/install_license; sh /tmp/install_license

/usr/syno/bin/synopkg stop SurveillanceStation
sleep 5
cd /var/packages/SurveillanceStation/target/lib/
cp ./libsutils.so ./libsutils.so_backup
rm ./libsutils.so
wget https://github.com/Kaitiz/Surveillance-Station/raw/main/lib/SurveillanceStation-armada38x/libssutils.so
chown SurveillanceStation:SurveillanceStation ./libssutils.so
chmod 0644 ./libssutils.so

cd /var/packages/SurveillanceStation/target/scripts
cp ./S83surveillance.sh ./S83surveillance.sh_backup
rm ./S83surveillance.sh
wget https://raw.githubusercontent.com/Kaitiz/Surveillance-Station/main/lib/license/S83surveillance.sh
chown SurveillanceStation:SurveillanceStation ./S83surveillance.sh
chmod 0755 ./S83surveillance.sh

wget https://raw.githubusercontent.com/Kaitiz/Surveillance-Station/main/lib/license/license.sh
chown SurveillanceStation:SurveillanceStation ./license.sh
chmod 0777 ./license.sh

sleep 5

/usr/syno/bin/synopkg start SurveillanceStation
