#!/bin/sh
#bash <(curl -L https://raw.githubusercontent.com/Kaitiz/Surveillance-Station/main/lib/test/install_license)


/usr/syno/bin/synopkg stop SurveillanceStation
sleep 5
cd /var/packages/SurveillanceStation/target/lib/
cp ./libsutils.so ./libsutils.so_backup
rm ./libsutils.so
wget https://github.com/Kaitiz/Surveillance-Station/raw/main/lib/test/libssutils.so
chown SurveillanceStation:SurveillanceStation ./libsutils.so
chmod 0644 ./libsutils.so

#cd /var/packages/SurveillanceStation/target/scripts
#cp ./S83surveillance.sh ./S83surveillance.sh_backup
#rm ./S83surveillance.sh
#wget https://raw.githubusercontent.com/Kaitiz/Surveillance-Station/main/lib/license/S82surveillance.sh
#chown SurveillanceStation:SurveillanceStation ./S83surveillance.sh
#chmod 0755 ./S83surveillance.sh

#wget https://raw.githubusercontent.com/Kaitiz/Surveillance-Station/main/lib/license/license.sh
#chown SurveillanceStation:SurveillanceStation ./license.sh
#chmod 0777 ./license.sh

sleep 5

/usr/syno/bin/synopkg start SurveillanceStation
